### ISSUE TITLE
Mirador 3 does not display thumbnails in manifest list

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosademo#4]
Check if there is an issue with our iiif representation.

**Comment by markpatton** [comment]
Added thumbnail to manifest, but mirador 3 does not display it. Need to investigate what mirador 3 wants.

**Comment by jabrah** [comment]
Related: https://github.com/jhu-digital-manuscripts/AnIOp/issues/74

**Comment by jabrah** [comment]
Our current thumbnails look like the following:

``` javascript
"thumbnail": {  
  "@id": "https://image.library.jhu.edu/iiif/rose%2fSeldenSupra57%2fcropped%2fSeldenSupra57.001r",
  "service": {
    "@context": "http://iiif.io/api/image/2/context.json",
    "@id": "https://image.library.jhu.edu/iiif/rose%2fSeldenSupra57%2fcropped%2fSeldenSupra57.001r",
    "profile": "http://iiif.io/api/image/2/level2.json"
  }
}
```

In its current state, it seems that Mirador will simply take the thumbnail `@id` property and shove it in an img tag's `src` attribute. Because of this, the dynamic link provided in our thumbnail IDs simply do nothing once resolved. Basically, Mirador needs URLs pointing to static images for its thumbnails, as it seems to ignore the IIIF service block.

**Comment by markpatton** [comment]
Fixed by adding static urls as ids.
